---
title: "Patient reported and clinical outcomes following surgery for proximal humerus fractures"
toc: false
---

### Why:

Breaks (fractures) of the upper arm are the most common osteoporotic fractures after wrist and hip fractures in the elderly population. Multiple breaks can occur following an everyday fall on an outstretched arm.

This project is about studying this common shoulder injury, where doctors want to clarify the best way to do surgery.

By adding this information to what has already been learned from a similar study done at Christchurch Hospital, we plan a bigger study involving multiple hospitals in different cities. The future study will look at different surgeries for this type of fracture to determine which works best.

### Who:

We are looking back at past cases where people had surgery for this type of fracture in Otago and Canterbury.

### What:

We have already checked records of patients at Dunedin Hospital for some clinical information, with approval from the hospital, and we will now ask these patients about their experiences after surgery of their pain, and activities of daily living.

### How:

We will invite patients to attend a clinic to assess their shoulder range of movement and to complete two questionnaires. The clinic can be in person at Dunedin Hospital or virtually via a video call.

### More information

Thank you for taking time to read about our study. For further details please contact the Principal Investigator (Mr Fraser Harrold, <fraser.harrold@otago.ac.nz>).

*This project has been reviewed and approved by the University of Otago Human Ethics Committee (Health). Reference: H24/0085*
