---
title: "Surgical and non-surgical treatments for osteoarthritis"
toc: false
---

### Why:

Osteoarthritis is a common long-term condition and is a frequent presentation in primary care (16,000 new cases recorded per year in Aotearoa).

Initial management (patient education, exercise, and weight management) often does not reach patients as recommended and this results in long-term use of pain-relieving medications before joint replacement surgery.

This type of surgery dominates the public health system costs for osteoarthritis.

Results will provide insight into:

* how to most effectively select patients who will benefit most from surgery,

* to demonstrate the unmet need for surgery, and

* to make the case to funders and decision makers for funding and resourcing to increase capacity to undertake surgery.

### Who:

This is a study of patients coming to see a surgeon for the first time whether they have a total joint replacement or receive non-surgical treatments for late-stage osteoarthritis.

### What:

We will look at the patients’ experiences over a period of two years from the first appointment at Dunedin Hospital and examine the impact of rationing surgery by evaluating the effectiveness and cost-effectiveness of total joint replacement compared to non-surgical care.

### How:

We will invite patients who attend an orthopaedic surgeon clinic appointment and those who have been seen in the past two years at Dunedin Hospital. We will collect patients’ perceptions of how pain affects their quality of life and functioning.

We are inviting all patients at their first specialist appointment to complete two questionnaires. We will contact them again to repeat the same questionnaires:

* six months following this appointment

* 12 months after the appointment and

* 24 months after the appointment.

These can be completed online with the link being sent via email, through a brief telephone call from one of the research team or posted out to be completed on paper.

### More information

Thank you for taking time to read about our study. For further details please contact the Principal Investigator (Dr Ross Wilson, <ross.wilson@otago.ac.nz>).

*This project has been reviewed and approved by the University of Otago Human Ethics Committee (Health). Reference: H24/0081*
