project:
  type: website
  output-dir: docs

website:
  title: "CMOR"

  navbar:
    title: "Centre for Musculoskeletal Outcomes Research<br><i>University of Otago</i>"
    logo: _images/cmor-logo.jpg
    background: "white"
    right:
      - href: index.qmd
        text: "*Kāinga*<br>Home"
      - text: "*Mahi*<br>Our work"
        menu:
          - href: our-work.qmd
            text: Overview
          - href: hrc-programme.qmd
            text: "HRC Programme 2022--2027"
          - href: oarnet.qmd
            text: Osteoarthritis Aotearoa Research Network
      - href: publications.qmd
        text: "*Puka rangahau*<br>Publications"
      - href: events.qmd
        text: "*Kaupapa*<br>Events"
      - href: news.qmd
        text: "*Ngā Karere*<br>News"
      - href: our-people.qmd
        text: "*Ō mātou tāngata*<br>Our people"
      - href: teaching.qmd
        text: "*Whakaako*<br>Teaching"

  sidebar:
    style: "floating"
    logo: _images/cmor-logo.jpg
    contents:
      - text: <b>CMOR</b>
      - text: University of Otago
      - text: <i class="bi bi-geo-alt-fill"></i> Dunedin, New Zealand
      - text: <i class="bi bi-link-45deg"></i> Website
        href: https://www.otago.ac.nz/dsm-surgery/research/cmor/index.html
      - text: <i class="bi bi-twitter"></i> Twitter
        href: https://twitter.com/CMOR_Otago
      - text: <i class="bi bi-github"></i> GitHub
        href: https://github.com/uo-cmor

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    appendix-style: plain
    csl: vancouver.csl
    language:
      section-title-citation: "Recommended citation:"
      appendix-attribution-cite-as: " "



