---
title: "HRC Programme 2022--2027"
subtitle: "Project 2a: Filling gaps in OA knowledge: What are the long-term impacts of ligament injury?"
toc-depth: 3
---

### Research questions

What are the long-term impacts of ligament injury?

### Design and methods

This study will investigate the long-term impacts of ligament injury, including the risk of early-onset knee OA, using data from the IDI on all ligament injury claims made to ACC, equity of subsequent health and economic outcomes, including OA diagnosis data from primary care drawn from our current HRC-funded project (18/442). The IDI-based analyses will use matching methods to construct cohorts of similar individuals varying only in the treatment/exposure of interest (ligament injury, opioid prescribing). By using the whole-of-population datasets and extensive linked data available in the IDI, we will have sufficient data to construct high-quality matching between ‘case’ and ‘control’ groups, and will follow established best practices in the construction, diagnostic testing, and refinement of these matching models. Outcomes will be compared between the matched cohorts using standard methods such as linear, logistic, and survival models. Analyses will also be stratified by age, gender, and ethnicity (and the matching models constructed to support these subgroup analyses) to identify groups at high risk of inequitable outcomes. These analyses will all build on existing projects currently underway, including an HRC-funded Health Delivery Research grant (20/1164) for analysis of the ligament injury data and Otago Medical Research Foundation- and H.S & J.C Anderson Trust-funded research on opioid use around TJR. The IDI is unique and world-leading in the extent of linked individual-level, population-wide data available, allowing us to provide data and results of international significance.

### Research team:

Abbott (project leadership), Pryymachenko (data analysis expertise, esp. IDI); Wilson (advice on statistical analysis, IDI expertise, and simulation model inputs); Ligament injuries: Whittaker, Young; Kairangahau Māori rōpū, equity analyses interpretation: Mutu-Grigg, Kidd, Bell.
