---
title: "HRC Programme 2022--2027"
subtitle: "Project 1: Allocative efficiency in the management of hip and knee OA"
toc-depth: 3
---

### Research questions

This project will evaluate the allocative efficiency and equity consequence of varying the funding mix and treatment provision for preventive, early-, mid-, and late-stage OA interventions. Specific research questions will include: What is the cost-effectiveness of ligament injury prevention strategies to reduce early OA incidence? What is the cost-effectiveness of delivering co-ordinated care and core interventions in the public health system? What is the cost-effectiveness of strategies to reduce the use of opioids before and after TJR? What is the cost-effectiveness of varying the disease stage and symptom profile at which TJR is offered? What mix of these competing investments gleans the greatest benefits and equity gains? The Project will respond to WAI 2575 and provide data to Project 4.

### Design and methods

We will develop and validate a computer simulation model of hip and knee OA incidence and progression, symptoms, healthcare and economic costs, and treatment pathways, building on the skills, expertise, and codebase developed in our recent HRC-funded project (15/263) in which we developed and applied a new simulation model (the NZ-MOA model) for knee OA. We have used the NZ-MOA model for several completed and in-progress studies within our projects HRC 15/263 and 18/442, including an estimate of the lifetime health losses attributable to knee OA in Aotearoa, the future healthcare costs and demand for joint replacement, the lifetime cost-effectiveness of multiple early- and mid-stage knee OA interventions, and a programme evaluation for the Ministry of Health (MoH).

The state-transition design of the NZ-MOA model is well-suited to evaluating the costs and effects of interventions over time, but is not suitable for evaluating the allocative efficiency of varying the funding mix across the disease course. Addressing these crucial questions requires a novel model structure able to capture changes in capacity constraints across the health sector associated with different funding allocations. We will therefore develop for this project a new model, based on a discrete event simulation (DES) framework, that is explicitly designed to incorporate capacity constraints and resource allocation across the health sector. A recent systematic review of models used in economic evaluation for OA found that the vast majority were simple decision-tree models or Markov state-transition models that are similarly unable to evaluate resource allocation across the disease course. Previous work by NI Marshall identified an absence of research modelling resource use requirements, constraints, and allocative efficiency. Our proposed research will therefore be leading edge internationally.

In brief, a DES model consists of a population of hypothetical simulated individuals, each with attributes (e.g. age, sex, disease state); a set of health events, such as disease incidence, initiation of treatment, or occurrence of adverse events, that can happen to the individuals; resources such as healthcare facilities or workers required to process, for example, patients undergoing a particular treatment; and the flow of time over which individuals enter the model, events occur, and outcomes are measured. This provides a flexible and powerful way to simulate clinical reality across the course of a disease.

An advantage of the DES framework is the model transparency afforded by the ability to follow individuals’ and groups’ disease course and clinical pathways through the model, along with the decision criteria and probability distributions applied at each step. This allows rigorous evaluation of the face validity of the model structure, assumptions, and input data, including by non-technical reviewers. This will give end-users and decision-makers confidence in our modelling methods, outputs, and recommendations to support translation, uptake, and impact.

Fitting a realistic DES model requires a wealth of data to inform the key relationships between patient attributes, event occurrence, and resulting outcomes. In this project we will bring together a range of existing data and modelling resources, including the world-leading linked individual-level, population-wide data available in the Statistics NZ Integrated Data Infrastructure (IDI); existing data from national population datasets; modelling expertise; data and results from our previous HRC-funded projects (07/199, 07/200, 11/124, 15/263, 18/442) and current project (21/526); and systematic reviews and meta-analyses of intervention effectiveness. The research conducted in Project 2 will build on these existing resources and data to fill key knowledge gaps and provide additional required model inputs. Model structure, input data, and outputs will be rigorously validated (face, internal, external, predictive) using established best-practice methodology, including cross-model validity. Equity will be a core consideration in model design, inputs, and analyses.

The model will be used to evaluate the healthcare and societal costs and HRQoL outcomes, at the population level, of various strategies for the prevention or management of OA throughout the disease course. These are evaluated by running the same simulated population cohort through alternative intervention scenarios, each involving different funding allocations or treatment pathways for individuals with OA. The lifetime population healthcare and societal costs and HRQoL outcomes will be compared across the different scenarios to evaluate intervention cost-effectiveness. An advantage of individual-level simulation models is the ability to run equity analyses on sub-populations, such as Māori, to identify scenarios that offer the greatest equity gains (i.e. strongest potential to reduce disparities).

### Research team

Wilson (simulation modelling), Abbott (project leadership), Pryymachenko (IDI data analysis expertise); Schofield, Marshall & Clarke (simulation modelling and health economic analyses), Kairangahau Māori rōpū (Mutu-Grigg, Kidd, Bell: advice on equity analyses and interpretation), Whittaker (advice on injury prevention and treatment intervention outcomes), Stokes (advice primary care, interface with secondary care, and health systems implications, network, dissemination and impact activities).
