---
title: "HRC Programme 2022--2027"
subtitle: "Project 3: He Oranga mō te whanau -- Improving outcomes for people with hip and knee OA and co-morbidities"
toc-depth: 3
---

### Research questions

Does a novel, culturally acceptable exercise therapy, dietary education, and self-management intervention, in addition to usual care, result in superior self-reported and objectively measured physical and physiological outcomes in people with multimorbidity, compared with usual care only? Is it cost-effective? What are the equity consequences? Project 3 will provide data to Proj. 1 & 4.

### Background

This project focuses on multimorbidity. Multimorbidity affects >42% of Aotearoa peoples over age 45, with Māori and Pasifika disproportionately affected. Physical activity has positive effects on at least 26 LTCs including cardiovascular disease, T2D, COPD, depression and health outcomes in overweight and obesity, however the pain and disability of OA is a barrier to physical activity. Exercise therapy supported by patient education is effective in overcoming that barrier. The high prevalence of multimorbidity in Māori and Pacific patients requires the health system reorientate health-care delivery around multimorbidity, and deliver culturally safe lifestyle interventions. Multimorbidity in which OA is one condition is termed OA and comorbidity.

This project builds on the previous research of the investigator team. The unique contribution of this Aotearoa project is our focus on people with OA and comorbidity, and adapting interventions to the unique Aotearoa context.

PI Abbott’s group have conducted extensive stakeholder research on the preferences and priorities of a cross-section of stakeholders in the treatment of OA. We conducted focus groups with people with OA (n=11), Māori (n=5), policymakers (national & local healthcare delivery) (n=7), healthcare providers (n=10), and OA experts (n=5). This revealed that presence of co-morbid conditions, attitudes and beliefs, culturally safe practices, social support factors, and accessibility were among the key themes important to stakeholders.

NI Skou’s team has to date completed a series of focus group interview projects, co-development of an intervention programme with people with multimorbidity and health care providers, a feasibility study (manuscripts in preparation), and a qualitative study nested within the programme feasibility trial aimed to investigate participants’ and health care providers experiences with the exercise and self-management intervention developed by NI Skou’s team, and assess intervention acceptability.

NI Coppell’s team have conducted a non-randomised 6-month comparative feasibility trial of a dietary-focussed weight loss programme in patients with prediabetes, with economic evaluation, in Hawke’s Bay funded by the MoH, Hawke’s Bay Medical Research Foundation and the NZ Society for the Study of Diabetes. The feasibility of implementing the novel nurse-delivered Prediabetes Intervention Package (PIP) within the primary care setting, in patients with recently diagnosed prediabetes, was shown, and intervention fidelity was shown to be very good. The study enrolled eight general practices in the Napier-Hastings region, recruiting 172 with prediabetes and overweight or obesity. Patient interviews (9 men and 10 women, comprising of 8 Māori, 2 Pacific and 9 non-Māori non-Pacific), indicated the intervention was very well received . A current HRC funded (16/344) follow-up study uses the same intervention but with additional follow-up support, providing valuable feasibility, process and implementation insights. The project also established feasibility of cost-effectiveness analysis from a health service perspective. Strong engagement with all intervention practice nurses was established.

### Design and methods

This project will use a 4-phase approach: 1) co-refinement of intervention with ethnically diverse Aotearoa context; 2) pilot study; 3) randomised controlled trial with economic evaluation and process evaluation; and 4) implementation toolkit production. We will develop an exercise therapy and education program based on MOBILIZE and existing recommendations for exercise, diet, lifestyle change, and strategies to facilitate behavioural changes. The lifestyle education will incorporate the PIP in its entirety (i.e. 1x 30 minute and 5x 15 minute dietary assessment and goal setting sessions) provided by a trained practice nurse experienced in the intervention (NI Tangiora), and guidelines-informed healthy lifestyle education and self-management sessions. The exercise therapy protocols, proven effective in the MOA Trial, include aerobic, strength, agility, and flexibility, will be provided by Māori physiotherapists. The exercise therapy has been specifically designed to use minimal equipment, be readily delivered in outpatient or primary care settings and transferable to home use. Strong interdisciplinary collaboration and a high degree of patient involvement throughout the entire research process are at the heart of the project to ensure relevance to patients and the health care system and to make sure that the project is implementable in clinical practice. A core design focus is to optimise the uptake of the programme within culturally diverse health care settings.

In Phase 1 we will co-develop, with an ethnically diverse sample of stakeholders, the content and format of the intervention building on the extensive development phases of the MOBILIZE, MOA and PIP studies. Using a qualitative and Mātauranga Māori approach, interviews will be conducted with patients and their whānau with OA and comorbidity, healthcare consumers and providers, to determine their preferences and expectations. In the event of COVID restrictions, we will either delay up to 6 months or recruit fully vaccinated.

In Phase 2 we will recruit and interview patients and whānau with multimorbidity meeting the inclusion/exclusion criteria (below) in a pilot study of all aspects of the full trial protocol below. Semi-structured interviews will explore the challenges and benefits of the programme, preferences for delivery, barriers and facilitators of access and adherence. Qualitative research will use culturally aligned approaches, sampling improved, not-improved, male, female, Māori, and non-Māori (n=30).

Phase 3 is a randomized trial with process evaluation and economic evaluation. The study hypothesis is that the personalized exercise therapy and lifestyle education program will result in superior HRQoL (primary), physical function, and cardiovascular risk factors (including glycated haemoglobin HbA1c), and will be cost-effective from health system and societal perspectives compared with usual care. Usual care is the ideal comparison for establishing incremental effects over status quo health delivery, and for evaluation of cost-effectiveness of implementation. All healthcare consumption in both groups is measured using the Otago Costs and Consequences Questionnaire.

Participants with OA and co-morbidity (i.e. multimorbidity) will be recruited through Health Hawkes Bay practices and Hastings Hospital orthopaedic outpatients and randomly assigned to either the supported exercise therapy and education programme or usual care

Inclusion criteria: adults aged 35-70 meeting the NICE clinical diagnostic criteria for OA and at least one of the following: T2D or prediabetes, heart disease (heart failure or coronary heart disease), hypertension, COPD, or depression. Having other comorbidities does not exclude participation. Exclusion criteria: Participation in supervised systematic exercise for one of their diseases within the last 3 months; Patients with: an unstable health condition or at risk of serious adverse events; with life expectancy of less than 12 months; with psychosis disorders, post-traumatic stress disorder, Obsessive Compulsive Disorder, attention deficit hyperactivity disorder, autism, anorexia nervosa/bulimia nervosa or with an illness related to substance or alcohol abuse; not independently mobile in the community, not willing or available to participate for the intervention duration; or unable to comprehend the recruitment or intervention processes.

Implementation will be conducted and reported in accordance with the Consolidated Framework for Implementation Research (CFIR) and He Pikinga Waiora Implementation Framework (HPWIF)153, 154. The process evaluation will comply with best-practice guidance using qualitative, quantitative and mixed-methods for analysis of outcome measures in which several NIs have expertise. The CFIR is a pragmatic structure for evaluating implementation research, that has been widely used to inform such evaluations including those similar to MOBILIZE. The HPWIF is a tool designed to improve the uptake of prevention and treatment programmes within culturally diverse health care settings, aimed at reducing health inequities and achieving health equity for Māori. The HPWIF is a 62-item tool that utilizes in-depth interviews and online surveys in the domains of cultural-centeredness, community engagement, systems thinking, and integrated knowledge translation to assess and inform successful future implementation. Mixed-methods framework analysis will be based in a Kaupapa Māori theoretical grounding.

To ensure the highest quality trial design, we have submitted our proposal to ANZMUSC peer-review for endorsement. We will register the trial on www.ANZCTR.org.au and publish full protocol details on https://OSF.io We will report the results using CONSORT (+ extensions) and CHEERS standards.

Phase 4: Should the trial results be positive; we will develop training and implementation resources and impact activities to support uptake at scale across other settings (an implementation toolkit). This proposal responds to Priorities 5 and 6 of the Academy of Medical Sciences priorities for multimorbidity (develop tools and deploy strategies).

### Research team

Coppell, Abbott, Skou, Wilson, Bell (kairangahau Māori), Brooking (kairangahau Māori), Tangiora (kairangahau Māori), Wawatai-Aldrich (kairangahau Māori), Bennell.

**Key relationships:** Health Hawkes Bay, Cape Physio Māori Physiotherapists Leah Tuhi, Blake Taylor, Judy Brown; Consumer Advisory Group, Māori Advisory Group (kairangahau Māori above, Cape Physio cultural liaison Brenda Wainohu, locally recruited Māori representatives).

### Would you like information about participating in the trial?

If you have a sore hip or knee as well as at least one other long-term condition (like diabetes, heart disease, high blood pressure, mild-to-moderate depression) **and** you live in Hawkes Bay, [click here](https://uo-cmor.github.io/moa-pip-trial/information-for-participants) to learn more.
