---
title: "News"
---

## 2022

* [Cost-effectiveness of the Mobility Action Programme for people with osteoarthritis -- CMOR YouTube Channel](https://www.youtube.com/@cmor_otago/videos)

* [Urgent call for greater help for osteoarthritis -- RNZ *Morning Report*](https://www.rnz.co.nz/national/programmes/morningreport/audio/2018847746/urgent-call-for-greater-help-for-osteoarthritis)

* [Research suggests early osteoarthritis intervention could save $1b per year -- RNZ News](https://www.rnz.co.nz/news/national/441354/research-suggests-early-osteoarthritis-intervention-could-save-1b-per-year)

* [$5 million for research on osteoarthritis - Otago Daily Times](https://www.odt.co.nz/news/dunedin/campus/5-million-research-osteoarthritis)

## 2020

* [Otago researcher sets wheels in motion on #rOAdtrip for osteoarthritis change -- New Zealand Doctor](https://www.nzdoctor.co.nz/article/undoctored/otago-researcher-sets-wheels-motion-roadtrip-osteoarthritis-change)

* [Prof riding 3000km to show osteoarthritis treatment message -- Otago Daily Times](https://www.odt.co.nz/news/dunedin/prof-riding-3000km-show-osteoarthritis-treatment-message)

* [Otago researcher sets wheels in motion on #rOAdtrip for osteoarthritis change -- University of Otago](https://www.otago.ac.nz/news/news/otago732314.html)

* [Professor looks to make ‘real world impact’ to spread research knowledge -- Otago Bulletin Board, University of Otago](https://www.otago.ac.nz/otagobulletin/news/otago732647.html)

* [Time for a joint effort -- Otago Daily Times](https://www.odt.co.nz/news/dunedin/time-joint-effort)

* [The Prof passes through -- Martinborough Star](https://www.martinboroughstar.co.nz/the-prof-passes-through/)

## 2019

* [New Zealand’s knee replacement burden linked to alarming obesity rates -- NZ Herald](https://www.nzherald.co.nz/nz/news/article.cfm?c_id=1&objectid=12273335)

* [Cost of treating knee osteoarthritis and surgeries likely to increase, experts say -- Stuff.co.nz](https://www.stuff.co.nz/life-style/well-good/teach-me/116288347/cost-of-treating-knee-osteoarthritis-and-surgeries-likely-to-increase-experts-say)

## 2018

* [Nearly half of Kiwis predicted to be clinically obese in two decades’ time -- 1News](https://www.1news.co.nz/2018/07/04/new-zealand-needs-to-start-taking-high-obesity-rates-seriously-as-nearly-half-of-kiwis-predicted-to-be-clinically-obese-in-two-decades-time/)

* [Two million obese New Zealanders by 2038, study finds -- NZ Herald](https://www.nzherald.co.nz/nz/news/article.cfm?c_id=1&objectid=12083109)

* [Two Million Obese New Zealanders Predicted -- RNZ *Lately*](https://www.rnz.co.nz/national/programmes/lately/audio/2018703392/two-million-obese-new-zealanders-predicted)

## 2017

* [Osteoarthritis no knees-up for many NZers -- University of Otago](https://www.otago.ac.nz/news/news/releases/otago666522.html)

## 2015

* [A Joint Effort To Look After Arthritic Joints -- RNZ *Our Changing World*](https://www.rnz.co.nz/national/programmes/ourchangingworld/audio/20165042/a-joint-effort-to-look-after-arthritic-joints)

## 2014

* [Research raises questions about physiotherapy for hip osteoarthritis -- University of Otago](https://www.otago.ac.nz/news/news/otago071984.html)

* [One kind of therapy done well better than a mix: research -- Otago Daily Times](http://www.odt.co.nz/campus/university-otago/304074/one-kind-therapy-done-well-better-mix-research)

* [OA patients benefit long term from exercise or manual therapy -- MDedge | Rheumatology News](https://www.mdedge.com/rheumatology/article/88728/rheumatology/oa-patients-benefit-long-term-exercise-or-manual-therapy)

* [Easing pain and cost for arthritis sufferers -- Otago Daily Times](https://www.odt.co.nz/news/campus/university-of-otago/easing-pain-and-cost-arthritis-sufferers)

* [Joint Support Newsletter Online (March 2014) \[PDF\]](https://www.arthritis.org.nz/wp-content/uploads/2014/03/Joint-Support-March-2014-online1.pdf)

## 2013

* [Osteoarthritis improved by extra physiotherapy programmes -- University of Otago](https://www.otago.ac.nz/news/news/otago050882.html)

* [Research contributions recognised -- Otago Daily Timess](https://www.odt.co.nz/news/dunedin/research-contributions-recognised)

* [Osteoarthritis improved by extra physiotherapy -- Voxy](http://www.voxy.co.nz/health/osteoarthritis-improved-extra-physiotherapy-study/5/162181)

* [Moving ahead with osteoarthritis -- Otago Daily Times](https://www.odt.co.nz/news/dunedin/moving-ahead-osteoarthritis)

## 2012

* [Awards recognise up-and-coming Otago researchers -- Infonews](https://www.infonews.co.nz/news.cfm?id=90427)

* ['Joint Clinic' could be NZ model -- Otago Daily Times](https://www.odt.co.nz/news/dunedin/joint-clinic-could-be-nz-model)
