---
title: "*Te Anga Kaikōiwi o Aotearoa*<br>Osteoarthritis Aotearoa Research Network"
toc: false
---

*Te Anga Kaikōiwi o Aotearoa* | Osteoarthritis Aotearoa Research Network (OARnet) is a national, interdisciplinary network of researchers across Aotearoa. This initiative has secured initial funding support from the University of Otago, 2022-2026.

This national OA Research Network aims to: 1) Progress research excellence across the spectrum of research contributing to new knowledge relevant to osteoarthritis. 2) Extend research strength in Aotearoa New Zealand by advancing OA research and facilitating national and international collaboration. 3) Build capability and capacity in OA research by supporting research training and early- and mid-career development of the OA research workforce.

Current initiatives: 1) Developing a Consumer, Patient & Public Partnership Panel 2) Developing an Early- and Mid-Career Researcher (EMCR) support network 3) Providing continuing researcher development short-course and webinar opportunities.

## OARnet short courses

### An introduction to qualitative research for clinician researchers

OARnet offered an in-person short course and workshop in Auckland over two ½ days in the week of July 17th, 2023.

This course and workshop was led by Dr Sam Bunzli (Griffith University), that was first developed by the OPUS group in Australia (see: <https://opus-tjr.org.au/programs/quali-research/>)

### An introduction to tikanga Māori principles and practices for early-career researchers in Aotearoa

We are working with an outstanding, nationally recognised centre of excellence in Māori education and training to develop a short course for new kairangahau wanting to improve their cultural competence, cultural safety, and effectiveness in engaging with Māori and achieving advances in health equity in Aotearoa. We aim to offer this course in June 2024.  

#### Early-Career Researchers
OARnet is able to offer these short courses **at no cost** to qualifying OARnet member researchers within 6 years of completing your PhD or enrolled in a graduate research degree (honours, masters, PhD). This **OARnet Scholarship Award** is made possible through a 100% subsidy on the registration fee, by successful application -- there are a generous number of Awards available, but apply early to avoid missing out. Priority will be given to postdocs and PhD students who articulate in their application a strong justification of the benefit of attending this course.

You can become an OARnet member if you meet the criteria for membership: i.e. you are active in research related to osteoarthritis.

**Contact:** Professor Haxby Abbott Director, Osteoarthritis Aotearoa Research Network (OARnet) Centre for Musculoskeletal Outcomes Research, University of Otago Medical School

## OARnet 2023 Annual Conference

### November 2, Dunedin

Te Anga Kaikōiwi o Aotearoa New Zealand Osteoarthritis Research Network held its [second annual conference](https://events.otago.ac.nz/2023-oa-summit) in Dunedin as part of the OA Summit (Nov 3rd 2023), and the OA Model of Care Co-design Workshop (the morning of Nov 4th, 2023). 

This attracted double the number of registrants as the inaugural 2022 event, for an exciting programme of invited speakers and platform presentations, as well as a poster session.

These were peer-reviewed / quality-assured presentation opportunities in the following categories:

1. Early Career Researcher category (Research thesis student or postdoc within 6 full-time-equivalent years of PhD or professional graduation), either:
- 5-in-5 (5 slides in 5 minutes) (preferred) or
- 12 minute platform presentations (for reports of completed research only)
2. Open category: either:
- 5-in-5 (5 slides in 5 minutes) (preferred) or
- 12 minute platform presentations (for reports of completed research only)

**A limited number of OARnet Scholarship Travel Awards were available, for eligible Early Career Researchers, by application.**

## OARnet 2024 Annual Conference

We are in the early stages of planning a 2024 OARnet Annual Conference, most likely to be held in Christchurch, in November 2024.
