---
title: "HRC Programme 2022--2027"
subtitle: "Project 2: Risks, Impacts, Equity, and Cost-Effectiveness"
toc-depth: 3
---

## Project 2a: What are the long-term impacts of ligament injury

### Research questions

What are the long-term impacts of ligament injury?

### Design and methods

This study will investigate the long-term impacts of ligament injury, including the risk of early-onset knee OA, using data from the IDI on all ligament injury claims made to ACC, equity of subsequent health and economic outcomes, including OA diagnosis data from primary care drawn from our current HRC-funded project (18/442). The IDI-based analyses will use matching methods to construct cohorts of similar individuals varying only in the treatment/exposure of interest (ligament injury, opioid prescribing). By using the whole-of-population datasets and extensive linked data available in the IDI, we will have sufficient data to construct high-quality matching between ‘case’ and ‘control’ groups, and will follow established best practices in the construction, diagnostic testing, and refinement of these matching models. Outcomes will be compared between the matched cohorts using standard methods such as linear, logistic, and survival models. Analyses will also be stratified by age, gender, and ethnicity (and the matching models constructed to support these subgroup analyses) to identify groups at high risk of inequitable outcomes. These analyses will all build on existing projects currently underway, including an HRC-funded Health Delivery Research grant (20/1164) for analysis of the ligament injury data and Otago Medical Research Foundation- and H.S & J.C Anderson Trust-funded research on opioid use around TJR. The IDI is unique and world-leading in the extent of linked individual-level, population-wide data available, allowing us to provide data and results of international significance.

### Research team:

Abbott (project leadership), Pryymachenko (data analysis expertise, esp. IDI); Wilson (advice on statistical analysis, IDI expertise, and simulation model inputs); Ligament injuries: Whittaker, Young; Kairangahau Māori rōpū, equity analyses interpretation: Mutu-Grigg, Kidd, Bell.

## Project 2b: What are the impacts of opioid use around TJR surgery?

### Research questions

What are the impacts of opioid use around TJR surgery?

### Design and methods

This study will investigate the prevalence, risks and impacts of opioid use around TJR surgery, using data from the IDI on all ligament injury claims made to ACC, equity of subsequent health and economic outcomes, including OA diagnosis data from primary care drawn from our current HRC-funded project (18/442); The IDI-based analyses will use matching methods to construct cohorts of similar individuals varying only in the treatment/exposure of interest (ligament injury, opioid prescribing). By using the whole-of-population datasets and extensive linked data available in the IDI, we will have sufficient data to construct high-quality matching between ‘case’ and ‘control’ groups, and will follow established best practices in the construction, diagnostic testing, and refinement of these matching models. Outcomes will be compared between the matched cohorts using standard methods such as linear, logistic, and survival models. Analyses will also be stratified by age, gender, and ethnicity (and the matching models constructed to support these subgroup analyses) to identify groups at high risk of inequitable outcomes. These analyses will all build on existing projects currently underway, including an HRC-funded Health Delivery Research grant (20/1164) for analysis of the ligament injury data and Otago Medical Research Foundation- and H.S & J.C Anderson Trust-funded research on opioid use around TJR. The IDI is unique and world-leading in the extent of linked individual-level, population-wide data available, allowing us to provide data and results of international significance.

### Research team

Abbott (project leadership), Pryymachenko (data analysis expertise, esp. IDI); Wilson (advice on statistical analysis, IDI expertise, and simulation model inputs); Joint replacement surgeries: Mutu-Grigg, Choong, Gwynne-Jones, Young, Dowsey; Opioid use: Choong, Dowsey, Buchbinder, Stokes; Kairangahau Māori rōpū, equity analyses interpretation: Mutu-Grigg, Kidd, Bell.

## Project 2c: The cost-effectiveness of TJR in the Aotearoa health system

### Research questions

What is the cost-effectiveness of TJR in the Aotearoa health system? How does the cost-effectiveness of TJR vary by disease stage, patient characteristics, and symptom profile at surgery? Is TJR delivered equitably in Aotearoa?

### Design and methods

#### Cost-effectiveness of TJR

Joint replacement surgery dominates the public health system costs for OA. It is highly effective and cost-effective, but exactly when it is best offered is not known. This project will investigate the cost-effectiveness of TJR surgery at differing levels of severity, using our data collected from patients undergoing TJR at Dunedin Hospital. The analysis will use a fuzzy regression discontinuity (RD) design. RD designs are a powerful method to estimate causal, quasi-experimental treatment effects from non-random allocation, by exploiting arbitrary treatment allocation rules in real-world settings. Due to increasing demand and limited capacity, access to TJR in the public healthcare sector is rationed in Aotearoa. At first specialist assessment, patients are evaluated using the NZ Orthopaedic Association Prioritisation Tool. A threshold Prioritisation Tool score (varying over time to reflect shifts in supply and demand) is used to determine eligibility for surgery: patients scoring above the threshold are considered for surgery, while those falling below are referred back to their GP for ongoing non-surgical management. As access is determined by local health system capacity to deliver surgery within prescribed waiting times, patients scoring just above and just below the threshold are otherwise similar and would both be expected to gain from surgery. The fuzzy RD design exploits the discontinuity in the likelihood of being offered surgery around the threshold value to identify the causal effect of TJR despite the non-random allocation of patients to surgical and non-surgical treatment. HRQoL and treatment costs over up to two years post-operatively will be estimated to conduct a cost-effectiveness analysis of surgical versus non-surgical management for these patients. This will be a unique study in the field.

#### Equity of access to joint replacement surgery

We have previously described the equity of access to hip and knee TJR surgery in the public health system from 2006–2013 using the MoH’s National Minimum Dataset (NMDS), and projected total knee replacement surgery rates (Māori, non-Māori) to 2038 using the NZ Joint Registry (NZJR). While we found no inequity of access for Māori, non-urban, and more deprived subpopulations in the public health system, this does not provide the complete picture required for accurate modelling and equity analyses, as it fails to capture TJR provided by ACC and the private sector. We will overcome that limitation by leveraging two world-leading Aotearoa data resources: the NZJR and the IDI. We aim to link NZJR data with the IDI, and replicate the methods described in our earlier research110. Linking the important NZJR data resource would be a significant contribution to research capability in Aotearoa using the IDI. We have engaged with the Board of the NZJR and StatsNZ (Sept. 2021); should linking not be possible we will again use the MoH NMDS data and NZJR data directly, which is possible but with limitations of weaker ethnicity data, greater uncertainty in subpopulation identification, and blends ACC with private sector funded TJRs. This project will be led by Orthopaedic Surgeons Dr John Mutu-Grigg (Ngati Kahu, Te Rarawa) and Dr Simon Young (NZ Joint Registry Board member) as NZJR liaison.

### Research team

Abbott (project leadership), Pryymachenko (data analysis expertise, esp. IDI); Wilson (advice on statistical analysis, IDI expertise, and simulation model inputs); Joint replacement surgeries: Mutu-Grigg, Choong, Gwynne-Jones, Young, Dowsey; Kairangahau Māori rōpū, equity analyses interpretation: Mutu-Grigg, Kidd, Bell.
